### ISSUE TITLE
Invoke AuditQueryCode setup when installing with ZPM

### ISSUE THREAD

**Issue by sduncan01** [sduncan01/CubeAuditing#3]
Request from @evshvarov; see pull request #2:
Could you please also add the invoke/call to enable logging by running the following command in that namespace:
set ^DeepSee.AuditQueryCode = "do ##class(Sample.AuditQueryLog).InsertQuery(.%dsResultSet,%dsQueryText,%dsCubeName)"

**Comment by sduncan01** [comment]
@SergeyMi37 commented on pull request #2 that "Invoke does not seem to allow you to call the code by xecute? Apparently you need to create a new method."

I'm not sure what the best approach is here - if it would be helpful to create a new method in Sample.AuditQueryLog to run this command, I can do that. @evshvarov, do you have any suggestions?

**Comment by sduncan01** [comment]
fixed by PR #4 from @SergeyMi37

**Comment by evshvarov** [comment]
@sduncan01  - could you please publish a new release with Package Manager option On - to publish the package in the repository?

**Comment by sduncan01** [comment]
@evshvarov I just published v0.1.2, which I thought I had submitted last week, but was actually a draft waiting for me to click "Publish". What this doesn't have is any documentation on ZPM installation. Am I correct that the relevant command is just this?
USER>zpm "install CubeAuditing"

**Comment by evshvarov** [comment]
To make the app be published as ZPM module in the public repository you are
expected to turn on the Publish as ZPM Package check box.
Docs <https://docs.openexchange.intersystems.com/solutions/submit/>
Details
<https://community.intersystems.com/post/objectscript-package-auto-publishing-now-available-open-exchange>
Could you please make a new release with this checkbox turned on?

**Comment by sduncan01** [comment]
Done, thanks for clarifying.

**Comment by evshvarov** [comment]
Published - you can check it e.g. here
<https://zpm-explorer.contest.community.intersystems.com/csp/irisapp/explorer.html>
.

Now everyone can install it with:
zpm "install cubeauditing"
Thanks!
